#include <stdio.h>

#ifndef HASHFUNCTION_H
#define HASHFUNCTION_H


/**Function that creates a key for the hash table based on using % with the size
 *of the hash table and the first letter of the given data
 *
 *@param tableSize is the number of rows in the hashTable
 *@param key is a void* to hash data, in this case holding a word
 *@return the key generated by the function
 */
int hashFunction (size_t tableSize, void *key);

#endif
